# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e08cbc2426be0868e63730ad7ce237e1d4b764dccaea6ef2989c8b37294aea5923ba06fc4e2e408516d2b73824f2b0b388bef02826b2252d69e3d527f5ff7969

test:
  secret_key_base: 7b52b916b948ab179393b642d5d371fce5304c7aa13c0ea668de8f292d52b9a8f3708fbe86e5e2b7a6012264ebdd9025bf31a4eefcbfa891f59808ed326c059a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
