# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 842716105984bc24c5a3f3e9a112998d1f9f880000532343995266dbe82da2b771816a75caac60ed1c8e0e995d8909ead6cf6679933296c98af804c59a8aef9c

test:
  secret_key_base: 588c31d8cf457c45953764f3680067ac80666b7a511ef7fb8826688b76d8dd6ff1ee8b867a389486bd68b78a86305bc0cda4f92a08570f77921138c5908774e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
